config/routes.rb
ModelTest::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:index, :show, :destroy, :create, :update]
  scope '/user' do
    resources :posts, only: [:new, :edit]
  end
  resources :users, only: [:show, :index]

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :body, length: {minimum: 5, maximum: 500}
  validates :user_id, presence: true

  before_validation :omit_whitespaces_from_title

  private
  def omit_whitespaces_from_title
    self.title = self.title.chomp
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'layouts/my_layout', only: [:show]
  before_filter :check_signed_in, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_post_by_id, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @post }
      format.xml  { render xml:  @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new()
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.json { head 200 }
        format.xml  { head 200 }
      end
    else
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.json { render "create", status: 400 }
        format.xml  { head 400 }
      end
    end
    # redirect_to posts_path
  end

  def edit
  end

  def update
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.save
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post_by_id
    @post = current_user.posts.find(params[:id])
  end

  def check_signed_in
    if !signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.password == params[:password]
      sign_in_user(user)
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
      render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user, serializer: UserSerializer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in_user(user)
    cookies[:user_id] = user.id
    current_user = user
  end

  def sign_out
    cookies.delete(:user_id)
    current_user = nil
  end

  def current_user
    @current_user = @current_user || User.find_by_id(cookies[:user_id])
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="menu">
      <%= link_to "Posts", posts_path %>
      <% if signed_in? %>
      | <%= link_to "Sign out", session_path(1), method: "Delete" %>
      <% else %>
      | <%= link_to "Sign in", new_session_path %>
      <% end %>
   </div>
   <br/>
   <button onclick="toggleMenu();" class="menu-toggle-btn" type="button">Toggle menu</button>
<p>
  ________________________________
</p>
<%= yield %>

</body>
</html>

app/views/layouts/my_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="menu">
    <%= link_to "Posts", posts_path %>
    |
    <%= yield :edit_post_link %>
    |
    <%= yield :delete_post_link %>
    <% if signed_in? %>
    | <%= link_to "Sign out", session_path(1), method: "Delete" %>
    <% else %>
    | <%= link_to "Sign in", new_session_path %>
    <% end %>
  </div>
  <br/>
  <button onclick="toggleMenu();" class="menu-toggle-btn" type="button">Toggle menu</button> 
  <p>
    ________________________________
  </p>
  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :body %>
<%= f.text_field :body %>
<br>
<%= f.submit %>
<% end %>

app/views/posts/create.json.erb
{"<%= "error" %>":"<%= "Some error!" %>"}

app/views/posts/edit.html.erb
<% content_for :title do %>
  <% "Edit your post here." %>
<% end %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :title do %>
<% "List of posts." %>
<% end %>
<%= link_to "New post", new_post_path %>

<table>
  <tr>
    <td>
      <h3>Title</h3>
    </td>
    <td>
      Edit post
    </td>
    <td>
      Delete post
    </td>
  </tr>
  <% @posts.each do |p| %>
    <tr>
      <td>
        <%= link_to p.title, p %>
      </td>
      <td>
        <a href="#" data-preview="<%= p.body[0..19] %>">Preview</a>
      </td>
      <td>
        <%= link_to "Edit", edit_post_path(p.id) %>
      </td>
      <td>
        <%= link_to "Delete", p, method: :delete, data: { confirm: "Really?" } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<% content_for :title do %>
<% "Create a new post here." %>
<% end %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :title do %>
<% @post.title %>
<% end %>

<% content_for :edit_post_link do %>
<% link_to "Edit this post", edit_post_path(@post) %>
<% end %>

<% content_for :delete_post_link do %>
<% link_to "Delete this post", @post, method: 'Delete' %>
<% end %>

<h3><%= @post.title %></h3>
<p>
  <%= @post.body %>
</p>
<p>
  Author: <%= @post.user.name %>
</p>